platform: linux/arm64

pipeline:
  amd64-binaries:
    image: ubuntu
    secrets: [ scwrc ]
    commands:
      - echo "$SCWRC" > ~/.scwrc
      - chmod 600 ~/.scwrc
      - apt update
      - apt install -y ssh wget
      - ssh-keygen -q -f /root/.ssh/id_rsa -N ""
      - wget "https://github.com/scaleway/scaleway-cli/releases/download/v1.17/scw_1.17_arm64.deb" -O /tmp/scw.deb
      - dpkg -i /tmp/scw.deb 
      - rm -f /tmp/scw.deb
      - scw create --commercial-type=c2s --tmp-ssh-key --name="drone-cast-$DRONE_COMMIT_SHA" ubuntu-bionic
      - scw start -w drone-cast-$DRONE_COMMIT_SHA
      - sleep 10
      - scw cp ./ drone-cast-$DRONE_COMMIT_SHA:/root/
      - scw exec drone-cast-$DRONE_COMMIT_SHA 'bash -c "apt update && apt-get install -y squashfs-tools wget ruby build-essential python libogg-dev"'
      - scw exec drone-cast-$DRONE_COMMIT_SHA 'bash -c "cd /root/ && wget https://github.com/slee047/node-packer/archive/1.6.0-8.11.4.tar.gz && tar xzf 1.6.0-8.11.4.tar.gz && chmod +x ./node-packer-1.6.0-8.11.4/bin/nodec"'
      - scw exec drone-cast-$DRONE_COMMIT_SHA 'bash -c "wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash"'
      - scw exec drone-cast-$DRONE_COMMIT_SHA 'bash -c "source $HOME/.nvm/nvm.sh && nvm install 8.11.4"'
      - scw exec drone-cast-$DRONE_COMMIT_SHA 'bash -c "source $HOME/.nvm/nvm.sh && cd /root/Cast/ && ../node-packer-1.6.0-8.11.4/bin/nodec ./server.js >/tmp/buildlog 2>&1"'
      - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$(scw inspect -f '{{.PublicAddress.IP}}' drone-cast-$DRONE_COMMIT_SHA):/root/Cast/a.out ./
      - mkdir dist
      - mv a.out dist/cast-$DRONE_TAG-linux-amd64
      - scw stop -t drone-cast-$DRONE_COMMIT_SHA
    # when:
    #   event: tag
      
  arm64-binaries:
    image: ubuntu
    secrets: [ scwrc ]
    commands:
      - echo "$SCWRC" > ~/.scwrc
      - chmod 600 ~/.scwrc
      - apt update
      - apt install -y ssh wget
      - ssh-keygen -q -f /root/.ssh/id_rsa -N ""
      - wget "https://github.com/scaleway/scaleway-cli/releases/download/v1.17/scw_1.17_arm64.deb" -O /tmp/scw.deb
      - dpkg -i /tmp/scw.deb 
      - rm -f /tmp/scw.deb
      - scw create --commercial-type=arm64-8gb --tmp-ssh-key --name="drone-cast-arm64-$DRONE_COMMIT_SHA" ubuntu-bionic
      - scw start -w drone-cast-arm64-$DRONE_COMMIT_SHA
      - sleep 10
      - scw cp ./ drone-cast-arm64-$DRONE_COMMIT_SHA:/root/
      - scw exec drone-cast-arm64-$DRONE_COMMIT_SHA 'bash -c "apt update && apt-get install -y squashfs-tools wget ruby build-essential python libogg-dev"'
      - scw exec drone-cast-arm64-$DRONE_COMMIT_SHA 'bash -c "cd /root/ && wget https://github.com/slee047/node-packer/archive/1.6.0-8.11.4.tar.gz && tar xzf 1.6.0-8.11.4.tar.gz && chmod +x ./node-packer-1.6.0-8.11.4/bin/nodec"'
      - scw exec drone-cast-arm64-$DRONE_COMMIT_SHA 'bash -c "wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash"'
      - scw exec drone-cast-arm64-$DRONE_COMMIT_SHA 'bash -c "source $HOME/.nvm/nvm.sh && nvm install 8.11.4"'
      - scw exec drone-cast-arm64-$DRONE_COMMIT_SHA 'bash -c "source $HOME/.nvm/nvm.sh && cd /root/Cast/ && ../node-packer-1.6.0-8.11.4/bin/nodec ./server.js >/tmp/buildlog 2>&1"'
      - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$(scw inspect -f '{{.PublicAddress.IP}}' drone-cast-arm64-$DRONE_COMMIT_SHA):/root/Cast/a.out ./
      - mv a.out dist/cast-$DRONE_TAG-linux-arm64
      - scw stop -t drone-cast-arm64-$DRONE_COMMIT_SHA
    # when:
    #   event: tag

  github_release:
    image: plugins/github-release:arm64
    secrets: [ github_token ]
    files: dist/*
    when:
      event: tag

branches:
  include: [ master, build-binaries ]