language: node_js
node_js:
  - "6.1"

os:
  - linux
  - osx

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wget; fi
  - wget -O /tmp/release-2.2.0.tar.gz https://github.com/megastep/makeself/archive/release-2.2.0.tar.gz && cd /tmp/ && tar -xzf release-2.2.0.tar.gz

script:
  - cp `which node` ./node
  - npm install
  - /tmp/makeself-release-2.2.0/makeself.sh `pwd` `node server.js` "Cast 1.0" /tmp/cast