language: node_js
node_js:
- '8'

env:
    global:
      - CXX=g++-4.8
      - QEMU_VER=v2.9.1
      - DOCKER_REPO=harbor.innovatete.ch/maartje/trainplanner
    matrix:
      - ARCH=amd64 ARCHREPO=amd64   QEMU_ARCH=x86_64
      - ARCH=armhf ARCHREPO=arm32v7 QEMU_ARCH=arm    
      - ARCH=arm64 ARCHREPO=arm64v8 QEMU_ARCH=aarch64
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo apt-get -y install qemu qemu-user-static qemu-user binfmt-support
  - docker run --rm --privileged multiarch/qemu-user-static:register
os:
- linux
script:
- npm test
- npm -g install babel-cli
- babel ./ -d /tmp/testbuild --minified --ignore 'node_modules/'
- npm install
- git reset --hard
- rm -fr node_modules/
- wget -N https://github.com/multiarch/qemu-user-static/releases/download/$QEMU_VER/x86_64_qemu-${QEMU_ARCH}-static.tar.gz
- tar -xvf x86_64_qemu-${QEMU_ARCH}-static.tar.gz
- docker build -t $DOCKER_REPO:$ARCH-$TRAVIS_COMMIT --build-arg ARCHREPO="$ARCHREPO" --build-arg QEMU_ARCH="$QEMU_ARCH" ./
