# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cast
email: maartje@eyskens.me
description: > # this means to ignore newlines until "baseurl:"
  Cast is a modern streaming solution built to accomodate the demands of modern radio streaming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://getca.st" # the base hostname & protocol for your site
github_username:  Innovate-Technologies

# Build settings
markdown: kramdown
