version: 1.0.{build}

clone_folder: C:\projects\cast

build_script:

- ps: >-

    Add-Type -assembly "system.io.compression.filesystem"

    cd C:\

    Start-FileDownload  https://github.com/slee047/node-packer/archive/1.6.0-10.9.0.zip -FileName C:\nodec.zip

    Start-FileDownload https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip -FileName C:\sqfs43-win32.zip

    Expand-Archive C:\sqfs43-win32.zip -DestinationPath C:\Windows
    
    Expand-Archive C:\nodec.zip -DestinationPath C:\

    ls C:\node-packer-1.6.0-10.9.0

    ls C:\node-packer-1.6.0-10.9.0\bin

    cd C:\projects\cast

    C:\node-packer-1.6.0-10.9.0\bin\nodec.bat server.js
    
    mv a.exe cast.exe

test: off

artifacts:

- path: cast.exe
  name: cast

cache:
  - node_modules 
  - '%APPDATA%\Local\Temp\1\nodec\'
  - '%APPDATA%\npm-cache'  

deploy:
  provider: GitHub
  auth_token:
    secure: +d2UJegJnX376FoU5evqeomUPD2zTCOHjSucBs3xmjz6Olc5H61DbF2Y1JF4qYYx
  artifact: cast.exe 
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
